### ISSUE TITLE
尊敬的作者您好，我运行的时候遇到了以下问题，能帮忙看下，告知我如何解决吗

### ISSUE THREAD

**Issue by Lain0o** [wangyendt/MicroHandGestureCollectorAndroid#1]
![Snipaste_2024-11-16_15-48-53](https://github.com/user-attachments/assets/f7a346a5-61b1-4016-8f75-60c16f3e04d5)
![Snipaste_2024-11-16_15-48-08](https://github.com/user-attachments/assets/9ec97300-c35d-42ac-a61d-8651e49be25e)

**Comment by wangyendt** [comment]
This is an auto-sent e-mail. 
 
I am sorry that currently I could not reply your e-mail. I will reply you as soon as possible.

**Comment by wangyendt** [comment]
Hi，Lain0o，直接注释掉这两行就行，lark-bot相关的代码没有实际使用。我更新了一版，可以试试

**Comment by Lain0o** [comment]
好的，谢谢您的回复
